
name: Echo

on:
  push:
   branches: main


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: echo
        run: |
          v=`echo "${{ github.event.head_commit.message }}"`
          msg=$(echo "${v##*\n}")
          echo $v
          sed -n ${3}p <<< "$v"
          echo "---------"
          echo "$v" | sed -n 3p
