
name: Echo

on:
  push:
   branches: main


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: echo
        run: |
          v=`echo "${{ github.event.head_commit.message }}"`
          msg=$(echo "${v##*\n}")
          echo $v
          sed -n ${3}p <<< "$v"
