
name: Bump version

on:
  push:
   branches: main


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Make new version variable
        run: |
          echo ${{ github.event.head_commit.message }}
