
name: Echo

on:
  push:
   branches: main


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Make new version variable
        run: |
          echo ${{ github.event.head_commit.message }} | head -1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.1.13
          
