name: yaml up

on:
  push:
   branches: main


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Get current version from pyproject.toml
        run: | 
          version_line=$(sed '3q;d' pyproject.toml)
          old_version=`echo "${version_line}" | cut -d'"' -f 2`
          echo "old_version=${old_version}" >> $GITHUB_ENV
      - name: Get commit message (without description)
        run: |
          commit_message=`echo "${{ github.event.head_commit.message }}" | head -1`
          echo "commit_message=${commit_message}" >> $GITHUB_ENV
      - name: Make new version variable
        run: |
          gem install semver
          semver tag
