name: Run unittests

on:
  push:

jobs:
  unittests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.1.13
      - name: print version
        run: poetry version
