name: Bump version

on:
  push:
   branches: main


jobs:
  change_sth:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: make file.txt with current version from pyproject.toml
        run: | 
          version_line=$(sed '2q;d' project.toml)
          echo ${version_line}
          old_version=`echo "$version_line" | cut -d'"' -f 2`
          echo ${old_version}
          echo "old_version=${old_version}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: bump
        run: |
          new_version=$(python script.py ${{ env.old_version }} ${{ github.event.head_commit.message }})
          echo "new_version=${new_version}" >> $GITHUB_ENV
      - name: change version in .toml
        run: sed -i 's/${{env.old_version}}/${{ env.new_version }}/g' project.toml
      - name: commit file.txt
        uses: EndBug/add-and-commit@v9
        with:
          message: 'vesion bump'
          add: 'project.toml'
      - name: tag adding
        if: ${{ env.new_version != env.old_version }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ env.new_version }}"
