# name: Bump version

# on:
#   push:
#    branches: main


# jobs:
#   change_sth:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: '0'
#       - name: Get current version from pyproject.toml
#         run: | 
#           version_line=$(sed '3q;d' pyproject.toml)
#           old_version=`echo "${version_line}" | cut -d'"' -f 2`
#           echo "old_version=${old_version}" >> $GITHUB_ENV
#       - name: Get commit message (without description)
#         run: |
#           commit_message=`echo "${{ github.event.head_commit.message }}" | head -1`
#           echo "commit_message=${commit_message}" >> $GITHUB_ENV
#       - name: Make new version variable
#         run: |
#           new_version=$(python script.py ${{ env.old_version }} ${{ env.commit_message }})
#           echo "new_version=${new_version}" >> $GITHUB_ENV
#       - name: Update version in pyproject.toml
#         run: sed -i 's/${{env.old_version}}/${{ env.new_version }}/g' pyproject.toml
#       - name: Commit version changes in pyproject.toml
#         uses: EndBug/add-and-commit@v9
#         with:
#           message: 'Automated version bump'
#           add: 'pyproject.toml'
#       - name: Add tag with new version
#         if: ${{ env.new_version != env.old_version }}
#         uses: rickstaa/action-create-tag@v1
#         with:
#           tag: "v${{ env.new_version }}"
